### ISSUE TITLE
VTK TypeError when rendering IsosurfaceBrowser object in QT widget

### ISSUE THREAD

**Issue by girdeux31** [marcomusy/vedo#1064]
I got this error when I try to render a IsosurfaceBrowser object in QT widget. It totally works with a RayCastingPlotter (see commented line in code). Vedo 2024.5.1 is used.

```
python3 vedo_qt_test_issue.py 
Traceback (most recent call last):
  File "/home/cmesado/Documents/08_PRUEBA/01_DicomFiles/vedo_qt_test_issue.py", line 37, in <module>
    window = MainWindow()
  File "/home/cmesado/Documents/08_PRUEBA/01_DicomFiles/vedo_qt_test_issue.py", line 22, in __init__
    self.plt = IsosurfaceBrowser(vol, qt_widget=self.widget)
  File "/home/cmesado/.local/lib/python3.10/site-packages/vedo/applications.py", line 1171, in __init__
    slider_isovalue(isovalue, "")  # init call
  File "/home/cmesado/.local/lib/python3.10/site-packages/vedo/applications.py", line 1162, in slider_isovalue
    self.renderer.AddActor(mesh)
TypeError: AddActor argument 1: method requires a VTK object
```

MWE addapted from https://github.com/marcomusy/vedo/blob/master/examples/other/qt_window3.py

```
import sys
from PyQt5 import Qt
from vedo import dataurl, Volume
from vedo.applications import IsosurfaceBrowser, RayCastPlotter
from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor

class MainWindow(Qt.QMainWindow):

    def __init__(self, parent=None):

        Qt.QMainWindow.__init__(self, parent)
        self.frame = Qt.QFrame()
        self.layout = Qt.QVBoxLayout()
        self.widget = QVTKRenderWindowInteractor(self.frame)

        vol = Volume(dataurl + 'head.vti')
        
        # works with RayCastingPlotter, but it doesn't with IsosurfaceBrowser
        # self.plt = RayCastPlotter(vol, qt_widget=self.widget)
        self.plt = IsosurfaceBrowser(vol, qt_widget=self.widget)
        self.plt.show()

        self.layout.addWidget(self.widget)
        self.frame.setLayout(self.layout)
        self.setCentralWidget(self.frame)
        self.show()

    def onClose(self):
        self.widget.close()

if __name__ == "__main__":

    app = Qt.QApplication(sys.argv)
    window = MainWindow()
    app.aboutToQuit.connect(window.onClose)
    app.exec_()
```

Since it works with RayCastingPlotter object, I'd say it is a bug. Let me know otherwise.

**Comment by marcomusy** [comment]
Thanks for reporting. Try again after
```
pip install -U git+https://github.com/marcomusy/vedo.git
```
