### ISSUE TITLE
AttributeError: partially initialized module 'vedo' has no attribute 'Cone' (most likely due to a circular import)

### ISSUE THREAD

**Issue by InFistLee** [marcomusy/vedo#1132]
Hello there, I am a newcomer of vedo. After installing vedo in MacOS, I followed the tutorial in vedo tutorial to write my first script:
```
import vedo
vedo.Cone().show(axes=1).close()
```
and I got following error:
```
Traceback (most recent call last):
  File "/Users/yuxinli/workspace/vedo/vedo.py", line 1, in <module>
    import vedo
  File "/Users/yuxinli/workspace/vedo/vedo.py", line 2, in <module>
    vedo.Cone().show(axes=1).close()
AttributeError: partially initialized module 'vedo' has no attribute 'Cone' (most likely due to a circular import)
```
These are what I have in my venv:
```
Package             Version
------------------- -----------
contourpy           1.2.1
cycler              0.12.1
fonttools           4.53.0
importlib_resources 6.4.0
kiwisolver          1.4.5
matplotlib          3.9.0
numpy               1.26.4
packaging           24.0
pillow              10.3.0
pip                 24.0
Pygments            2.18.0
pyparsing           3.1.2
python-dateutil     2.9.0.post0
setuptools          69.5.1
six                 1.16.0
vedo                2024.5.1
vtk                 9.3.0
wheel               0.43.0
zipp                3.19.1
```

**Comment by marcomusy** [comment]
Do not name vedo.py your script! 
But I guess you figured it out already :)
