### ISSUE TITLE
Vedo custom axes: TypeError: 'tuple' object does not support item assignment

### ISSUE THREAD

**Issue by FedeClaudi** [marcomusy/vedo#204]
Hi Marco, 

When trying to specify `zrange` while creating `CustomAxes` I get this error:
```
Traceback (most recent call last):
  File "/Users/federicoclaudi/miniconda3/envs/dev/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/federicoclaudi/miniconda3/envs/dev/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/federicoclaudi/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/federicoclaudi/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/../ptvsd/server/cli.py", line 361, in main
    run()
  File "/Users/federicoclaudi/.vscode/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/../ptvsd/server/cli.py", line 203, in run_file
    runpy.run_path(options.target, run_name="__main__")
  File "/Users/federicoclaudi/miniconda3/envs/dev/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/Users/federicoclaudi/miniconda3/envs/dev/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Users/federicoclaudi/miniconda3/envs/dev/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/federicoclaudi/Documents/Github/BrainRender/workspace.py", line 18, in <module>
    scene.render(camera='top')
  File "/Users/federicoclaudi/Documents/Github/BrainRender/brainrender/render.py", line 233, in render
    show(*self.actors, *self.actors_labels, **args_dict)
  File "/Users/federicoclaudi/miniconda3/envs/dev/lib/python3.7/site-packages/vedo/plotter.py", line 316, in show
    q=q,
  File "/Users/federicoclaudi/miniconda3/envs/dev/lib/python3.7/site-packages/vedo/plotter.py", line 1731, in show
    addons.addGlobalAxes(self.axes)
  File "/Users/federicoclaudi/miniconda3/envs/dev/lib/python3.7/site-packages/vedo/addons.py", line 1887, in addGlobalAxes
    asse = buildAxes(None, **plt.axes)
  File "/Users/federicoclaudi/miniconda3/envs/dev/lib/python3.7/site-packages/vedo/addons.py", line 1280, in buildAxes
    vbb[4], vbb[5] = zrange
TypeError: 'tuple' object does not support item assignment
```

This is the axes dict:
```
            axes = dict(
                axesLineWidth=3,
                tipSize=0.01,
                xtitle="AP (μm)",
                ytitle="DV (μm)",
                ztitle="LR (μm)",
                textScale=0.8,
                xTitleRotation=0,
                xFlipText=True,
                zrange = np.array([0, -atlas_shape[2]]),
                zValuesAndLabels = z_ticks
            )
```

and `np.array([-atlas_shape[2], 0])` is a 1d `np.array` with two elements.

**Comment by marcomusy** [comment]
Thanks for spotting the bug. Quick fix: in `vedo/addons.py` 
```python
    if useGlobal:
        vbb, ss, min_bns, max_bns = computeVisibleBounds()
        vbb = list(vbb) # so that we can modify it
```

**Comment by daizhirui** [comment]
I think this bug is not fixed completely. [compute_visible_bounds](https://github.com/marcomusy/vedo/blob/5358e850426a9dff47d3cc0a6ec8053db7da3711/vedo/addons.py#L1950) still returns `vbb` as a tuple sometimes with `use_global=True`. A quick fix is to add `vbb = list(vbb)` after line 1950 as well.
