### ISSUE TITLE
render new volume on same plot

### ISSUE THREAD

**Issue by rsavjanimdphd** [marcomusy/vedo#463]
Hi all, 

I would like to use vedo for volumetric rendering, but I would like to update the plot with a new volume render based off a slider value input. So, as the slider is moved, a new volume is rendered and displayed. Idea looks like this: 

```python
from vedo.pyplot import plot, histogram, show
from vedo import Volume, buildLUT, Plotter
import numpy as np
import nibabel as nib
import vtk
from vtk.util.numpy_support import vtk_to_numpy
import time
import vedo
import torch

# create slider
def slider1(widget, event):
    
    # get slider value
    value = widget.GetRepresentation().GetValue()
    value = value/100

    # linear interpolate between the two coords
    z = z_0*value + z_1*(1-value)

    # run interpolation
    moved = decodeZ(z, moving, model)

    # create the volume 
    vol = Volume(moved, c=bodyColors,  mapper='fixed')
    vol.mapper().SetClippingPlanes(planes)

    # plot
    plt.show(vol, interactive=False, camera=cam2, bg='black')

# initialize volume
vol = Volume(img, c=bodyColors,  mapper='fixed')
vol.mapper().SetClippingPlanes(planes)

# add slider
plt.addSlider2D(slider1, 0, 100, value=0,
            pos="bottom-right", title="Interpolate", c='blue')

plt.show(vol, interactive=True, camera=cam2, bg='black')

```

However, when the slider is moved, this gives the following error: 

```python
Traceback (most recent call last):
  File "volMotion.py", line 138, in slider1
    plt.show(vol, interactive=False, camera=cam2, bg='black')
  File "/home/savjani/anaconda3/lib/python3.8/site-packages/vedo/plotter.py", line 2354, in show
    self.allowInteraction()
  File "/home/savjani/anaconda3/lib/python3.8/site-packages/vedo/plotter.py", line 778, in allowInteraction
    self.interactor.DestroyTimer(self._repeatingtimer_id)
TypeError: DestroyTimer argument 1: an integer is required (got type NoneType)
```

There is likely a better way to update the plt with the new rendered volume, right? Thanks!

**Comment by marcomusy** [comment]
Hi, what about something like this
```python
from vedo.pyplot import plot, histogram, show
from vedo import Volume, buildLUT, Plotter
import numpy as np
# import nibabel as nib
import vtk
import time
import vedo
# import torch

# create slider
def slider1(widget, event):
    
    # get slider value
    value = widget.GetRepresentation().GetValue()

    # create the volume     
    vol_new = Volume(vedo.dataurl+"embryo.tif", c="Reds")
    vol_new.alpha([0, value/100]) # change alpha
    # vol_new.mapper().SetClippingPlanes(planes)
    
    # remove last and add the new one
    plt.pop().add(vol_new)

# initialize volume
vol = Volume(vedo.dataurl+"embryo.tif", c="Blues")
# vol.mapper().SetClippingPlanes(planes)

plt = Plotter(bg='k')
# add slider
plt.camera.SetPosition( [26837.691, -14228.966, 11606.141] )
plt.camera.SetFocalPoint( [6532.881, 4030.983, 5040.516] )
plt.camera.SetViewUp( [-0.126, 0.209, 0.97] )
plt.addSlider2D(slider1, 0, 10, value=5,
                pos="bottom-right", title="Interpolate", c='blue7')

plt.show(vol, resetcam=False)
```
![Screenshot from 2021-09-21 13-01-58](https://user-images.githubusercontent.com/32848391/134159609-c2eb6d28-23b2-4b37-8eb5-f637c4635a89.png)

you may find other examples in `examples/volumetric`, but also iin `vedo/applications.py` for sliders

**Comment by rsavjanimdphd** [comment]
This is perfect, thank you so much! I didn't realize that you can pop off actors/volume from the plot.

One more question, it takes a little while to render my new volume (1-2 s). Is there a way to control the slider to only run the slider function after the user has released the mouse? Otherwise, there is a very laggy feeling to generate the intermediate volumes along the slider path.  

Thanks!

**Comment by rsavjanimdphd** [comment]
@marcomusy - amazing, thank you so much! This is exactly what I was looking for.

**Comment by marcomusy** [comment]
From the next release you'll be able to do simply:
```
plt.addSlider2D(slider1, 0, 10, value=5, title="Interpolate", c='blue7', delayed=True)
```
