### ISSUE TITLE
bug for tetralize

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#742]
I may find a bug for `tetralize`, and the code to reproduce the bug is:

```
cone = vtk.vtkConeSource()
cone.SetCenter(256, 256, 0)
cone.SetRadius(100)
cone.SetHeight(200)
cone.Update()

cone = Mesh(cone.GetOutput())
coneActor = cone.tetralize(side=0.025, debug=True)
```

And the bug is:

```
.. tetralize(): subsampling and cleaning
2022-11-30 14:00:58.935 (   2.583s) [                ]    vtkExtractEdges.cxx:435   INFO| Executing edge extractor: points are renumbered
2022-11-30 14:00:58.937 (   2.585s) [                ]    vtkExtractEdges.cxx:551   INFO| Created 12 edges
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2021.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2021.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/qiang_zhang/Desktop/TCPDemo/main.py", line 121, in <module>
    coneActor = cone.tetralize(side=0.025, debug=True)
  File "D:\Anaconda\envs\work\lib\site-packages\vedo\mesh.py", line 2448, in tetralize
    elen = mag(points[edges][:, 0, :] - points[edges][:, 1, :])
IndexError: too many indices for array: array is 2-dimensional, but 12 were indexed
python-BaseException
```

The version of `vedo` is `2022.4.1`.

**Comment by marcomusy** [comment]
thanks for reporting, I think this issue was fixed in the master version:
```python
from vedo import *
cone = Cone()
tetcone = cone.tetralize(side=0.025, debug=True)
show(tetcone, axes=1)
```

<img width="223" alt="Screenshot 2022-11-30 at 10 10 03" src="https://user-images.githubusercontent.com/32848391/204755683-a83bd320-c7c9-4205-8664-5716098ddcb1.png">
