### ISSUE TITLE
`show(mode=6)` throws AttributeError: module vedo.vtkclasses has no attribute vtkInteractorStyleRubberBand3D

### ISSUE THREAD

**Issue by diablodale** [marcomusy/vedo#842]
Hi. Enjoying vedo 🙂 and found that when `Volume::show()` is called with `mode=5` or `mode=6`, I receive `AttributeError` and the app faults.

### Setup

* Microsoft Windows 11 [Version 10.0.22621.1413]
* windows python venv with Python 3.9.13
* vedo 2023.4.4
* vtk 9.2.6

### Repro

Setup code similar to the following. Pass to it either `mode=5` or `mode=6`

```python
vol = Volume(volume_data)
vol.show(mode=5)
```

### Result

mode=5 throws error and faults
```
Traceback (most recent call last):
  File "C:\repos-nobackup\dicom-render\doit2.py", line 60, in <module>
    vol.show(mode=5)
  File "C:\repos-nobackup\dicom-render\.venv\lib\site-packages\vedo\base.py", line 854, in show
    return vedo.plotter.show(self, **options)
  File "C:\repos-nobackup\dicom-render\.venv\lib\site-packages\vedo\plotter.py", line 293, in show
    _plt_to_return = plt.show(
  File "C:\repos-nobackup\dicom-render\.venv\lib\site-packages\vedo\plotter.py", line 3075, in show
    self.interactor.SetInteractorStyle(vtk.vtkInteractorStyleRubberBand2D())
AttributeError: module 'vedo.vtkclasses' has no attribute 'vtkInteractorStyleRubberBand2D'
```

mode=6 throws error and faults
```
Traceback (most recent call last):
  File "C:\repos-nobackup\dicom-render\doit2.py", line 60, in <module>
    vol.show(mode=6)
  File "C:\repos-nobackup\dicom-render\.venv\lib\site-packages\vedo\base.py", line 854, in show
    return vedo.plotter.show(self, **options)
  File "C:\repos-nobackup\dicom-render\.venv\lib\site-packages\vedo\plotter.py", line 293, in show
    _plt_to_return = plt.show(
  File "C:\repos-nobackup\dicom-render\.venv\lib\site-packages\vedo\plotter.py", line 3077, in show
    self.interactor.SetInteractorStyle(vtk.vtkInteractorStyleRubberBand3D())
AttributeError: module 'vedo.vtkclasses' has no attribute 'vtkInteractorStyleRubberBand3D'
```

**Comment by marcomusy** [comment]
Hi Dale, thanks for the detailed report of the problem, indeed a few imports where missing, I just pushed a new version with the fixes.
