### ISSUE TITLE
BaseVolume.operation Issue

### ISSUE THREAD

**Issue by DanKrsi** [marcomusy/vedo#852]
Hello, I am trying to add volumes together, but I get the following error:

new_vol = vol.operation("+", volume2 = vol.clone())
File ~\anaconda3\lib\site-packages\vedo\volume.py:524 in operation
  if utils.is_number(volume2):
File ~\anaconda3\lib\site-packages\vedo\utils.py:1183 in is_number
  float(n)
TypeError: float() argument must be a string or a number, not 'Volume'

Example code reproducing the error is below:
```
import numpy as np
from vedo import Volume, show

data_matrix = np.zeros([70, 80, 90], dtype=np.uint8)
data_matrix[ 0:30,  0:30,  0:30] = 1
data_matrix[30:50, 30:60, 30:70] = 2
data_matrix[50:70, 60:80, 70:90] = 3
vol = Volume(data_matrix, c=['white','b','g','r'], mode=1)
new_vol = vol.operation("+", volume2 = vol.clone())
```

After looking at the source code, I believe the issue if the elif statement:

```
if utils.is_number(volume2):
    K = volume2
    mat.SetConstantK(K)
    mat.SetConstantC(K)

elif volume2 is not None:  # assume image2 is a constant value
    mat.SetInput2Data(volume2.imagedata())

```

If this is the case, could this be fixed?
Thanks!

**Comment by marcomusy** [comment]
thanks for spotting this, It should be fixed in the master
```
pip install -U git+https://github.com/marcomusy/vedo.git
```

**Comment by DanKrsi** [comment]
Hey Marco, When I run that pip line, I get this :------------------------------------------------------------------------------------Collecting git+https://github.com/marcomusy/vedo.git  Cloning https://github.com/marcomusy/vedo.git to c:\users\daniel\appdata\local\temp\pip-req-build-hc1jzrs5  Running command git clone --filter=blob:none --quiet https://github.com/marcomusy/vedo.git 'C:\Users\Daniel\AppData\Local\Temp\pip-req-build-hc1jzrs5'  Resolved https://github.com/marcomusy/vedo.git to commit 3547928915a5cf9f9c1aea92b285f4ec833987c6  Preparing metadata (setup.py) ... error  error: subprocess-exited-with-error   × python setup.py egg_info did not run successfully.  │ exit code: 1  ╰─> [27 lines of output]      Traceback (most recent call last):        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_normalization.py", line 62, in safe_version          return str(packaging.version.Version(v))        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_vendor\packaging\version.py", line 197, in __init__          raise InvalidVersion(f"Invalid version: '{version}'")      setuptools.extern.packaging.version.InvalidVersion: Invalid version: '.2023.4.4.dev10'       During handling of the above exception, another exception occurred:       Traceback (most recent call last):        File "<string>", line 2, in <module>        File "<pip-setuptools-caller>", line 34, in <module>        File "C:\Users\Daniel\AppData\Local\Temp\pip-req-build-hc1jzrs5\setup.py", line 11, in <module>          setup(        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\__init__.py", line 108, in setup          return distutils.core.setup(**attrs)        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_distutils\core.py", line 147, in setup          _setup_distribution = dist = klass(attrs)        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\dist.py", line 483, in __init__          self.patch_missing_pkg_info(attrs)        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\dist.py", line 472, in patch_missing_pkg_info          dist._version = _normalization.safe_version(str(attrs['version']))        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_normalization.py", line 65, in safe_version          return str(packaging.version.Version(attempt))        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_vendor\packaging\version.py", line 197, in __init__          raise InvalidVersion(f"Invalid version: '{version}'")      setuptools.extern.packaging.version.InvalidVersion: Invalid version: '.2023.4.4.dev10'      [end of output]   note: This error originates from a subprocess, and is likely not a problem with pip.error: metadata-generation-failed × Encountered error while generating package metadata.╰─> See above for output. note: This is an issue with the package mentioned above, not pip.hint: See above for details.------------------------------------------------------------------------------------ Is there maybe a version number needed after ‘vedo’? Regards,Daniel Krsikapa|  Ph.D. StudentStructural and Multidisciplinary Systems Design GroupQueen’s University, Jackson Hall 21335 Fifth Field Company LaneKingston, ON, Canada, K7L 2N8Tel: (613) 533-2914http://my.me.queensu.ca/People/Kim/ From: Marco MusySent: Monday, April 17, 2023 5:10 AMTo: marcomusy/vedoCc: DanKrsi; AuthorSubject: Re: [marcomusy/vedo] BaseVolume.operation Issue (Issue #852) thanks for spotting this, It should be fixed in the masterpip install -U git+https://github.com/marcomusy/vedo.git—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by DanKrsi** [comment]
Hey Marco, when I run that pip line, I get this :

```
Collecting git+https://github.com/marcomusy/vedo.git
  Cloning https://github.com/marcomusy/vedo.git to c:\users\daniel\appdata\local\temp\pip-req-build-hc1jzrs5
  Running command git clone --filter=blob:none --quiet https://github.com/marcomusy/vedo.git 'C:\Users\Daniel\AppData\Local\Temp\pip-req-build-hc1jzrs5'
  Resolved https://github.com/marcomusy/vedo.git to commit 3547928915a5cf9f9c1aea92b285f4ec833987c6
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
 
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_normalization.py", line 62, in safe_version
          return str(packaging.version.Version(v))
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_vendor\packaging\version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: '.2023.4.4.dev10'
 
      During handling of the above exception, another exception occurred:
 
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Daniel\AppData\Local\Temp\pip-req-build-hc1jzrs5\setup.py", line 11, in <module>
          setup(
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\dist.py", line 483, in __init__
          self.patch_missing_pkg_info(attrs)
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\dist.py", line 472, in patch_missing_pkg_info
          dist._version = _normalization.safe_version(str(attrs['version']))
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_normalization.py", line 65, in safe_version
          return str(packaging.version.Version(attempt))
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_vendor\packaging\version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: '.2023.4.4.dev10'
      [end of output]
 
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
 
× Encountered error while generating package metadata.
╰─> See above for output.
 
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```
 
Is there maybe a version number needed after ‘vedo’?

**Comment by marcomusy** [comment]
that's very strange.. can you try again now?

`pip uninstall vedo`
`pip install -U git+https://github.com/marcomusy/vedo.git`

i've changed to `dev11` but I dont see the dot in vedo/version.py... as indicated in your error message: 
`Invalid version: '.2023.4.4.dev10'`

**Comment by DanKrsi** [comment]
Here is the result:

```
(base) C:\Users\Daniel>pip uninstall vedo
Found existing installation: vedo 2023.4.4
Uninstalling vedo-2023.4.4:
  Would remove:
    c:\users\daniel\appdata\roaming\python\python39\scripts\vedo.exe
    c:\users\daniel\appdata\roaming\python\python39\site-packages\vedo-2023.4.4.dist-info\*
    c:\users\daniel\appdata\roaming\python\python39\site-packages\vedo\*
Proceed (Y/n)? y
  Successfully uninstalled vedo-2023.4.4
```

```
(base) C:\Users\Daniel>pip install -U git+https://github.com/marcomusy/vedo.git
Collecting git+https://github.com/marcomusy/vedo.git
  Cloning https://github.com/marcomusy/vedo.git to c:\users\daniel\appdata\local\temp\pip-req-build-ocraq5su
  Running command git clone --filter=blob:none --quiet https://github.com/marcomusy/vedo.git 'C:\Users\Daniel\AppData\Local\Temp\pip-req-build-ocraq5su'
  Resolved https://github.com/marcomusy/vedo.git to commit 216b7e826e13771cab82ca02ebe581b0656e5c02
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_normalization.py", line 62, in safe_version
          return str(packaging.version.Version(v))
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_vendor\packaging\version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: '.2023.4.4.dev11'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Daniel\AppData\Local\Temp\pip-req-build-ocraq5su\setup.py", line 11, in <module>
          setup(
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\dist.py", line 483, in __init__
          self.patch_missing_pkg_info(attrs)
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\dist.py", line 472, in patch_missing_pkg_info
          dist._version = _normalization.safe_version(str(attrs['version']))
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_normalization.py", line 65, in safe_version
          return str(packaging.version.Version(attempt))
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_vendor\packaging\version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: '.2023.4.4.dev11'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

Also note im using Python 3.9.16 and pip 23.1

**Comment by marcomusy** [comment]
That's very strange......
what if you 
```
git clone https://github.com/marcomusy/vedo.git
cd vedo 
pip install .
```

**Comment by DanKrsi** [comment]
Here's what I get:

```
(base) C:\Users\Daniel>cd vedo

(base) C:\Users\Daniel\vedo>pip install .
Processing c:\users\daniel\vedo
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_normalization.py", line 62, in safe_version
          return str(packaging.version.Version(v))
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_vendor\packaging\version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: '.2023.4.4.dev11'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Daniel\vedo\setup.py", line 11, in <module>
          setup(
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\dist.py", line 483, in __init__
          self.patch_missing_pkg_info(attrs)
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\dist.py", line 472, in patch_missing_pkg_info
          dist._version = _normalization.safe_version(str(attrs['version']))
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_normalization.py", line 65, in safe_version
          return str(packaging.version.Version(attempt))
        File "C:\Users\Daniel\anaconda3\lib\site-packages\setuptools\_vendor\packaging\version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: '.2023.4.4.dev11'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by marcomusy** [comment]
Thanks @DanKrsi 
I've never seen this behavior... i'll try to reproduce it today on my windows pc..

**Comment by DanKrsi** [comment]
Hi Marco, sorry about that, I just tried on a different PC and it worked just fine. The issue must be on my end. I'll figure it out. Thanks!

**Comment by marcomusy** [comment]
No worries, happy to hear that, sometime anaconda misbehaves...
