### ISSUE TITLE
Slice error

### ISSUE THREAD

**Issue by mAxGarak** [marcomusy/vedo#882]
Examples with `msh.intersect_with_plane` (tried torus and bunny from `Mesh.slice`) produce the same error : AttributeError: module 'vedo.vtkclasses' has no attribute 'vtkPolyDataPlaneCutter'

**Comment by marcomusy** [comment]
Try the dev version:
```
pip install -U git+https://github.com/marcomusy/vedo.git
```

**Comment by mAxGarak** [comment]
I cant do that in Anaconda shell (or I dont know how). So, I have replaced `...\Anaconda3\Lib\site-packages\vedo\` files with those from github.
Now I get this error : module 'vtkmodules.all' has no attribute 'vtkPolyDataPlaneCutter', which seems to be a vtk error !

**Comment by marcomusy** [comment]
Hi, it's very easy, just copy and paste the pip command above in your anaconda terminal and hit return

**Comment by mAxGarak** [comment]
Sure, that's easy, and that's what I tried first, with this result :
```
Collecting git+https://github.com/marcomusy/vedo.git
  Cloning https://github.com/marcomusy/vedo.git to c:\users\user\appdata\local\temp\pip-req-build-qzs238is
  Running command git clone --filter=blob:none --quiet https://github.com/marcomusy/vedo.git 'C:\Users\Olivier\AppData\Local\Temp\pip-req-build-qzs238is'
  Resolved https://github.com/marcomusy/vedo.git to commit 02561362bf8a87fd65a0ad111eb78a1fde2e483f
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\_normalization.py", line 59, in safe_version
          return str(packaging.version.Version(v))
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\_vendor\packaging\version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: '.2023.4.4.dev28'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-req-build-qzs238is\setup.py", line 11, in <module>
          setup(
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\dist.py", line 491, in __init__
          self.patch_missing_pkg_info(attrs)
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\dist.py", line 480, in patch_missing_pkg_info
          dist._version = _normalization.safe_version(str(attrs['version']))
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\_normalization.py", line 62, in safe_version
          return str(packaging.version.Version(attempt))
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\_vendor\packaging\version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: '.2023.4.4.dev28'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

**Comment by marcomusy** [comment]
it looks like related to a setuptools problem ([here](https://github.com/pypa/setuptools/issues/3772)).

I would try:
1. `git clone https://github.com/marcomusy/vedo.git`
  `cd vedo/vedo`
  in `version.py` remove `.devXX`
  `cd ..`
  `pip install .`

Or

`conda deactivate`
`pip install -U git+https://github.com/marcomusy/vedo.git`

Or
 
install a fresh anaconda
