### ISSUE TITLE
module 'numpy' has no attribute 'bool'

### ISSUE THREAD

**Issue by nal10** [marcomusy/vedo#888]
Cannot convert volumes loaded from .nrrd to numpy arrays due to deprecated bool call:

```
import vedo

vedo.load('/path/to/file.nrrd')
/Users/nicholas.lusk/opt/miniconda3/envs/ng_link_env/lib/python3.9/site-packages/vtkmodules/util/numpy_support.py:74: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  _vtk_np = {vtkConstants.VTK_BIT:numpy.bool,
Traceback (most recent call last):

  File "/Users/opt/miniconda3/envs/ng_link_env/lib/python3.9/site-packages/IPython/core/formatters.py", line 345, in __call__
    return method()

  File "/Users/opt/miniconda3/envs/ng_link_env/lib/python3.9/site-packages/vedo/volume.py", line 58, in _repr_html_
    arr = self.thumbnail(azimuth=0, elevation=-60, zoom=1.4, axes=True)

  File "/Users/opt/miniconda3/envs/ng_link_env/lib/python3.9/site-packages/vedo/base.py", line 980, in thumbnail
    axes = vedo.addons.Axes(self)

  File "/Users/opt/miniconda3/envs/ng_link_env/lib/python3.9/site-packages/vedo/addons.py", line 3117, in Axes
    gxy = shapes.Grid(s=(xticks_float, yticks_float))

  File "/Users/opt/miniconda3/envs/ng_link_env/lib/python3.9/site-packages/vedo/shapes.py", line 3031, in __init__
    Mesh.__init__(self, [verts, faces], c, alpha)

  File "/Users/opt/miniconda3/envs/ng_link_env/lib/python3.9/site-packages/vedo/mesh.py", line 142, in __init__
    self._data = buildPolyData(inputobj[0], inputobj[1])

  File "/Users/opt/miniconda3/envs/ng_link_env/lib/python3.9/site-packages/vedo/utils.py", line 586, in buildPolyData
    source_points.SetData(numpy2vtk(vertices, dtype=np.float32))

  File "/Users/opt/miniconda3/envs/ng_link_env/lib/python3.9/site-packages/vedo/utils.py", line 447, in numpy2vtk
    varr = numpy_to_vtk(arr.astype(dtype), deep=deep)

  File "/Users/opt/miniconda3/envs/ng_link_env/lib/python3.9/site-packages/vtkmodules/util/numpy_support.py", line 164, in numpy_to_vtk
    arr_dtype = get_numpy_array_type(vtk_typecode)

  File "/Users/opt/miniconda3/envs/ng_link_env/lib/python3.9/site-packages/vtkmodules/util/numpy_support.py", line 94, in get_numpy_array_type
    return get_vtk_to_numpy_typemap()[vtk_array_type]

  File "/Users/opt/miniconda3/envs/ng_link_env/lib/python3.9/site-packages/vtkmodules/util/numpy_support.py", line 74, in get_vtk_to_numpy_typemap
    _vtk_np = {vtkConstants.VTK_BIT:numpy.bool,

  File "/Users/opt/miniconda3/envs/ng_link_env/lib/python3.9/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])

AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by marcomusy** [comment]
What version of vtk are you using?
try
```
pip install vtk -U
```

**Comment by nal10** [comment]
Thanks for the quick response. Updating vtk fixed the issue
